name: purepulse_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to pub.dev.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_core: ^2.24.2
  cloud_firestore: ^4.14.0
  firebase_messaging: ^14.7.10
  firebase_auth: 4.20.0
  firebase_auth_platform_interface: 7.3.0
  flutter_map: ^6.0.0
  latlong2: ^0.9.0
  
  # State Management
  provider: ^6.1.1
  
  # UI & Utilities
  flutter_svg: ^2.0.9
  google_fonts: ^6.1.0
  intl: ^0.20.2
  shared_preferences: ^2.2.2
  
  
  # API calls
  http: ^1.1.2
  
  # Charts
  fl_chart: ^0.65.0
  
  # Location
  geolocator: ^12.0.0
  geocoding: ^2.1.1

  # Google Generative AI
  google_generative_ai: ^0.1.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    # If you add Rive animations, you'll need a folder like this:
    - assets/