// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFna6SQGyzMD2c9Ho_9eaXVLbf3e0X39s',
    appId: '1:484097875003:web:6186f1975f9f0edf04901e',
    messagingSenderId: '484097875003',
    projectId: 'purepulse-fd912',
    authDomain: 'purepulse-fd912.firebaseapp.com',
    storageBucket: 'purepulse-fd912.firebasestorage.app',
    measurementId: 'G-JQP61JPRLX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEmifipPdAw_ko5GKtUk7ytu2q_3jJ9lc',
    appId: '1:484097875003:android:7522396c5087c95704901e',
    messagingSenderId: '484097875003',
    projectId: 'purepulse-fd912',
    storageBucket: 'purepulse-fd912.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpdr1zJ9zgVNXz9iW_5_peh-u8EXV3XWU',
    appId: '1:484097875003:ios:173f39557f0ebd2304901e',
    messagingSenderId: '484097875003',
    projectId: 'purepulse-fd912',
    storageBucket: 'purepulse-fd912.firebasestorage.app',
    iosBundleId: 'com.example.purepulseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpdr1zJ9zgVNXz9iW_5_peh-u8EXV3XWU',
    appId: '1:484097875003:ios:173f39557f0ebd2304901e',
    messagingSenderId: '484097875003',
    projectId: 'purepulse-fd912',
    storageBucket: 'purepulse-fd912.firebasestorage.app',
    iosBundleId: 'com.example.purepulseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFna6SQGyzMD2c9Ho_9eaXVLbf3e0X39s',
    appId: '1:484097875003:web:d095d437477d450f04901e',
    messagingSenderId: '484097875003',
    projectId: 'purepulse-fd912',
    authDomain: 'purepulse-fd912.firebaseapp.com',
    storageBucket: 'purepulse-fd912.firebasestorage.app',
    measurementId: 'G-6Z2XCD8PEC',
  );
}
